version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: katex
    versions:
    - 0.12.0
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: markdown-it
    versions:
    - 12.0.4
